apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: forum
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          volumes:
          - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: forum
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
