apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: forum
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.187.126
    path: /nfs/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: forum
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
