apiVersion: v1
kind: PersistentVolume
metadata:
  name: stat-pv
  namespace: forum
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.187.126
    path: /srv/nfs/stat
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stat-pvc
  namespace: forum
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
