apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forum-pipe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/imran-hg/forum-pipe1.git/forum-pipe'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
