apiVersion: v1
kind: PersistentVolume
metadata:
  name: forum-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.187.126
    path: /exports/forum-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: forum-nfs-pv
