apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: forum
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.187.126
    path: /nfs/static
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: forum
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
